// ──────────────────────────────────────────────
// Creature Battles — Move Registry
// ──────────────────────────────────────────────
// The 40 starter moves shipped in Phase 1.0. Coverage:
//   - At least one offensive move per type (physical or special)
//   - A handful of status moves (heal, buff, debuff, status inflict, weather, terrain)
//   - Classic familiar names players will recognize
//
// Additional moves can be added later by following this exact shape.
// Engine code reads ID, type, category, power, accuracy, priority,
// and any optional effect fields.
// ──────────────────────────────────────────────
import type { Move } from "../types/creature.js";

export const MOVES: Move[] = [
  // ── Normal ──
  {
    id: "tackle",
    name: "Tackle",
    type: "normal",
    category: "physical",
    power: 40,
    accuracy: 100,
    priority: 0,
    description: "A full-body tackle.",
  },
  {
    id: "body_slam",
    name: "Body Slam",
    type: "normal",
    category: "physical",
    power: 85,
    accuracy: 100,
    priority: 0,
    description: "A heavy body slam; may paralyze.",
    statusInflict: { condition: "paralysis", chance: 0.3 },
  },
  {
    id: "hyper_beam",
    name: "Hyper Beam",
    type: "normal",
    category: "special",
    power: 150,
    accuracy: 90,
    priority: 0,
    description: "A devastating beam of energy.",
  },
  {
    id: "quick_attack",
    name: "Quick Attack",
    type: "normal",
    category: "physical",
    power: 40,
    accuracy: 100,
    priority: 1,
    description: "A blindingly fast strike that always goes first.",
  },

  // ── Fire ──
  {
    id: "ember",
    name: "Ember",
    type: "fire",
    category: "special",
    power: 40,
    accuracy: 100,
    priority: 0,
    description: "A small flame. May burn.",
    statusInflict: { condition: "burn", chance: 0.1 },
  },
  {
    id: "flamethrower",
    name: "Flamethrower",
    type: "fire",
    category: "special",
    power: 90,
    accuracy: 100,
    priority: 0,
    description: "A scorching flame. May burn.",
    statusInflict: { condition: "burn", chance: 0.1 },
  },
  {
    id: "sunny_day",
    name: "Sunny Day",
    type: "fire",
    category: "status",
    power: 0,
    accuracy: 100,
    priority: 0,
    description: "Intensifies the sun for 5 turns.",
    weatherSet: "sun",
  },

  // ── Water ──
  {
    id: "water_gun",
    name: "Water Gun",
    type: "water",
    category: "special",
    power: 40,
    accuracy: 100,
    priority: 0,
    description: "A blast of water.",
  },
  {
    id: "surf",
    name: "Surf",
    type: "water",
    category: "special",
    power: 90,
    accuracy: 100,
    priority: 0,
    description: "A towering wave.",
  },
  {
    id: "rain_dance",
    name: "Rain Dance",
    type: "water",
    category: "status",
    power: 0,
    accuracy: 100,
    priority: 0,
    description: "Summons heavy rain for 5 turns.",
    weatherSet: "rain",
  },

  // ── Electric ──
  {
    id: "thunder_shock",
    name: "Thunder Shock",
    type: "electric",
    category: "special",
    power: 40,
    accuracy: 100,
    priority: 0,
    description: "An electric jolt. May paralyze.",
    statusInflict: { condition: "paralysis", chance: 0.1 },
  },
  {
    id: "thunderbolt",
    name: "Thunderbolt",
    type: "electric",
    category: "special",
    power: 90,
    accuracy: 100,
    priority: 0,
    description: "A powerful electric blast. May paralyze.",
    statusInflict: { condition: "paralysis", chance: 0.1 },
  },
  {
    id: "electric_terrain",
    name: "Electric Terrain",
    type: "electric",
    category: "status",
    power: 0,
    accuracy: 100,
    priority: 0,
    description: "Electrifies the field for 5 turns.",
    terrainSet: "electric",
  },

  // ── Grass ──
  {
    id: "vine_whip",
    name: "Vine Whip",
    type: "grass",
    category: "physical",
    power: 45,
    accuracy: 100,
    priority: 0,
    description: "A whip of vines.",
  },
  {
    id: "energy_ball",
    name: "Energy Ball",
    type: "grass",
    category: "special",
    power: 90,
    accuracy: 100,
    priority: 0,
    description: "A focused orb of natural energy.",
  },
  {
    id: "grassy_terrain",
    name: "Grassy Terrain",
    type: "grass",
    category: "status",
    power: 0,
    accuracy: 100,
    priority: 0,
    description: "Covers the field in grass for 5 turns.",
    terrainSet: "grassy",
  },

  // ── Ice ──
  {
    id: "icy_wind",
    name: "Icy Wind",
    type: "ice",
    category: "special",
    power: 55,
    accuracy: 95,
    priority: 0,
    description: "A chilling wind that lowers Speed.",
    statStageChange: { target: "opponent", stat: "speed", delta: -1, chance: 1 },
  },
  {
    id: "ice_beam",
    name: "Ice Beam",
    type: "ice",
    category: "special",
    power: 90,
    accuracy: 100,
    priority: 0,
    description: "A frigid beam. May freeze.",
    statusInflict: { condition: "freeze", chance: 0.1 },
  },
  {
    id: "hail",
    name: "Hail",
    type: "ice",
    category: "status",
    power: 0,
    accuracy: 100,
    priority: 0,
    description: "Summons a hailstorm for 5 turns.",
    weatherSet: "hail",
  },

  // ── Fighting ──
  {
    id: "karate_chop",
    name: "Karate Chop",
    type: "fighting",
    category: "physical",
    power: 50,
    accuracy: 100,
    priority: 0,
    description: "A high-crit chopping strike.",
    critRatio: 1,
  },
  {
    id: "close_combat",
    name: "Close Combat",
    type: "fighting",
    category: "physical",
    power: 120,
    accuracy: 100,
    priority: 0,
    description: "A reckless brawl; lowers Defense.",
    statStageChange: { target: "self", stat: "def", delta: -1, chance: 1 },
  },

  // ── Poison ──
  {
    id: "poison_sting",
    name: "Poison Sting",
    type: "poison",
    category: "physical",
    power: 15,
    accuracy: 100,
    priority: 0,
    description: "A poisonous stinger. May poison.",
    statusInflict: { condition: "poison", chance: 0.3 },
  },
  {
    id: "sludge_bomb",
    name: "Sludge Bomb",
    type: "poison",
    category: "special",
    power: 90,
    accuracy: 100,
    priority: 0,
    description: "A toxic sludge bomb. May poison.",
    statusInflict: { condition: "poison", chance: 0.3 },
  },
  {
    id: "toxic",
    name: "Toxic",
    type: "poison",
    category: "status",
    power: 0,
    accuracy: 90,
    priority: 0,
    description: "Badly poisons the target.",
    statusInflict: { condition: "poison", chance: 1 },
  },

  // ── Ground ──
  {
    id: "mud_shot",
    name: "Mud-Shot",
    type: "ground",
    category: "special",
    power: 55,
    accuracy: 95,
    priority: 0,
    description: "A flung gob of mud. Lowers Speed.",
    statStageChange: { target: "opponent", stat: "speed", delta: -1, chance: 1 },
  },
  {
    id: "earthquake",
    name: "Earthquake",
    type: "ground",
    category: "physical",
    power: 100,
    accuracy: 100,
    priority: 0,
    description: "A devastating ground tremor.",
  },

  // ── Flying ──
  {
    id: "wing_attack",
    name: "Wing Attack",
    type: "flying",
    category: "physical",
    power: 60,
    accuracy: 100,
    priority: 0,
    description: "A buffeting strike with broad wings.",
  },
  {
    id: "air_slash",
    name: "Air Slash",
    type: "flying",
    category: "special",
    power: 75,
    accuracy: 95,
    priority: 0,
    description: "A blade of air; high crit ratio.",
    critRatio: 1,
  },

  // ── Psychic ──
  {
    id: "confusion",
    name: "Confusion",
    type: "psychic",
    category: "special",
    power: 50,
    accuracy: 100,
    priority: 0,
    description: "A weak psychic attack. May confuse.",
    statusInflict: { condition: "confusion", chance: 0.1 },
  },
  {
    id: "psychic",
    name: "Psychic",
    type: "psychic",
    category: "special",
    power: 90,
    accuracy: 100,
    priority: 0,
    description: "A strong psychic pulse. May lower Sp. Def.",
    statStageChange: { target: "opponent", stat: "spDef", delta: -1, chance: 0.1 },
  },
  {
    id: "psychic_terrain",
    name: "Psychic Terrain",
    type: "psychic",
    category: "status",
    power: 0,
    accuracy: 100,
    priority: 0,
    description: "Charges the field with psychic energy for 5 turns.",
    terrainSet: "psychic",
  },

  // ── Bug ──
  {
    id: "bug_bite",
    name: "Bug Bite",
    type: "bug",
    category: "physical",
    power: 60,
    accuracy: 100,
    priority: 0,
    description: "A piercing bite.",
  },
  {
    id: "bug_buzz",
    name: "Bug Buzz",
    type: "bug",
    category: "special",
    power: 90,
    accuracy: 100,
    priority: 0,
    description: "A damaging sonic vibration.",
    statStageChange: { target: "opponent", stat: "spDef", delta: -1, chance: 0.1 },
  },

  // ── Rock ──
  {
    id: "rock_throw",
    name: "Rock Throw",
    type: "rock",
    category: "physical",
    power: 50,
    accuracy: 90,
    priority: 0,
    description: "A hurled rock.",
  },
  {
    id: "stone_edge",
    name: "Stone Edge",
    type: "rock",
    category: "physical",
    power: 100,
    accuracy: 80,
    priority: 0,
    description: "Sharp stones; high crit ratio.",
    critRatio: 1,
  },
  {
    id: "sandstorm",
    name: "Sandstorm",
    type: "rock",
    category: "status",
    power: 0,
    accuracy: 100,
    priority: 0,
    description: "Whips up a sandstorm for 5 turns.",
    weatherSet: "sandstorm",
  },

  // ── Ghost ──
  {
    id: "shadow_ball",
    name: "Shadow Ball",
    type: "ghost",
    category: "special",
    power: 80,
    accuracy: 100,
    priority: 0,
    description: "A blob of shadow. May lower Sp. Def.",
    statStageChange: { target: "opponent", stat: "spDef", delta: -1, chance: 0.2 },
  },

  // ── Dragon ──
  {
    id: "dragon_breath",
    name: "Dragon Breath",
    type: "dragon",
    category: "special",
    power: 60,
    accuracy: 100,
    priority: 0,
    description: "A shockwave of draconic energy. May paralyze.",
    statusInflict: { condition: "paralysis", chance: 0.3 },
  },
  {
    id: "dragon_claw",
    name: "Dragon Claw",
    type: "dragon",
    category: "physical",
    power: 80,
    accuracy: 100,
    priority: 0,
    description: "A slashing claw infused with draconic power.",
  },

  // ── Dark ──
  {
    id: "bite",
    name: "Bite",
    type: "dark",
    category: "physical",
    power: 60,
    accuracy: 100,
    priority: 0,
    description: "A sharp bite. May cause flinching.",
  },
  {
    id: "dark_pulse",
    name: "Dark Pulse",
    type: "dark",
    category: "special",
    power: 80,
    accuracy: 100,
    priority: 0,
    description: "A pulse of dark energy.",
  },

  // ── Steel ──
  {
    id: "iron_tail",
    name: "Iron Tail",
    type: "steel",
    category: "physical",
    power: 100,
    accuracy: 75,
    priority: 0,
    description: "A heavy iron-hardened tail. May lower Defense.",
    statStageChange: { target: "opponent", stat: "def", delta: -1, chance: 0.3 },
  },

  // ── Fairy ──
  {
    id: "fairy_wind",
    name: "Fairy Wind",
    type: "fairy",
    category: "special",
    power: 40,
    accuracy: 100,
    priority: 0,
    description: "A gust of fairy-touched wind.",
  },
  {
    id: "moonblast",
    name: "Moonblast",
    type: "fairy",
    category: "special",
    power: 95,
    accuracy: 100,
    priority: 0,
    description: "A blast of moonlight. May lower Sp. Atk.",
    statStageChange: { target: "opponent", stat: "spAtk", delta: -1, chance: 0.3 },
  },

  // ── Status / utility ──
  {
    id: "recover",
    name: "Recover",
    type: "normal",
    category: "status",
    power: 0,
    accuracy: 100,
    priority: 0,
    description: "Restores 50% of max HP.",
    statStageChange: { target: "self", stat: "hp", delta: 0, chance: 1 },
  },
  {
    id: "swords_dance",
    name: "Swords Dance",
    type: "normal",
    category: "status",
    power: 0,
    accuracy: 100,
    priority: 0,
    description: "Sharply raises Attack (+2 stages).",
    statStageChange: { target: "self", stat: "atk", delta: 2, chance: 1 },
  },
  {
    id: "calm_mind",
    name: "Calm Mind",
    type: "psychic",
    category: "status",
    power: 0,
    accuracy: 100,
    priority: 0,
    description: "Raises Sp. Atk.",
    statStageChange: { target: "self", stat: "spAtk", delta: 1, chance: 1 },
  },
  {
    id: "sleep_powder",
    name: "Sleep Powder",
    type: "grass",
    category: "status",
    power: 0,
    accuracy: 75,
    priority: 0,
    description: "Puts the target to sleep.",
    statusInflict: { condition: "sleep", chance: 1 },
  },
];

/** Convenience lookup map. */
export const MOVES_BY_ID: Record<string, Move> = Object.fromEntries(
  MOVES.map((move) => [move.id, move]),
);
